select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "C90", # mccabe
    "I",   # isort
    "N",   # pep8-naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "S",   # flake8-bandit
    "BLE", # flake8-blind-except
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "COM", # flake8-commas
    "C4",  # flake8-comprehensions
    "INP", # flake8-no-pep420
    "T20", # flake8-print
    "PYI", # flake8-pyi, type-hinting stub files
    "PT",  # flake8-pytest-style
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "ERA", # flake8-eradicate
    "PTH", # flake8-use-pathlib
    "PL",  # pylint
    "FLY", # flynt
    "NPY", # NumPy-specific rules
    "RUF", # Ruff-specific rules
]
ignore = ["ANN101", "ANN102", "UP006", "UP007", "ARG002", "PLR0913"]
unfixable = ["B"] # Avoid trying to fix flake8-bugbear violations.
target-version = "py39" # Assume Python 3.9.
extend-exclude = ["tests", "examples"]

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 12

[pydocstyle]
convention = "google"

# Ignore `F401` (unused import violations) in all `__init__.py` files.
[per-file-ignores]
"__init__.py" = ["F401"]
"__main__.py" = ["B008", "S101"]
"./**/tests/*.py" = ["S101"]     # Use of assert detected.

[isort]
force-single-line = true
